import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

import type { PluginDefinition } from "@gotify/sdk";
import type { Plugin } from "vite";

type PluginInput = {
	source: string;
	resolvedId: string;
};

type GenerateLoadPluginOptions = {
	output?: string;
	packageJson?: string;
	dependencyFields?: Array<"dependencies" | "devDependencies" | "optionalDependencies">;
};

function buildSource(pluginInputs: PluginInput[]): string {
	const imports = pluginInputs.map((input, index) => `import plugin${index} from ${JSON.stringify(input.source)};`);
	const pluginList = pluginInputs.map((_, index) => `plugin${index}`).join(", ");

	return `// Generated by scripts/generate-load-plugin.ts. Do not edit by hand.
${imports.join("\n")}

export const pluginDefinitions = [${pluginList}] as const;
`;
}

type PackageJsonShape = {
	dependencies?: Record<string, string>;
	devDependencies?: Record<string, string>;
	optionalDependencies?: Record<string, string>;
};

function isPluginDefinition(value: unknown): value is PluginDefinition {
	if (!value || typeof value !== "object") {
		return false;
	}

	const candidate = value as Record<string, unknown>;
	const manifest = candidate.manifest;
	return (
		typeof candidate.defaultConfig === "string" &&
		typeof candidate.plugin === "function" &&
		manifest !== null &&
		typeof manifest === "object" &&
		typeof (manifest as Record<string, unknown>).token === "string" &&
		typeof (manifest as Record<string, unknown>).name === "string" &&
		Array.isArray((manifest as Record<string, unknown>).capabilities)
	);
}

async function readDependencyNames(
	packageJsonPath: string,
	dependencyFields: GenerateLoadPluginOptions["dependencyFields"],
): Promise<string[]> {
	const packageJson = JSON.parse(await readFile(packageJsonPath, "utf8")) as PackageJsonShape;
	const names = new Set<string>();

	for (const field of dependencyFields ?? ["dependencies", "optionalDependencies"]) {
		for (const name of Object.keys(packageJson[field] ?? {})) {
			names.add(name);
		}
	}

	return [...names];
}

async function resolvePluginInputs(
	dependencyNames: string[],
	resolve: (id: string) => Promise<string | null>,
): Promise<PluginInput[]> {
	const pluginInputs: PluginInput[] = [];

	for (const source of dependencyNames) {
		let resolvedId: string | null = null;
		try {
			resolvedId = await resolve(source);
		} catch {
			continue;
		}
		if (!resolvedId || resolvedId.startsWith("\0")) {
			continue;
		}

		try {
			const imported = await import(pathToFileURL(resolvedId).href);
			if (isPluginDefinition(imported.default)) {
				pluginInputs.push({ source, resolvedId });
			}
		} catch {}
	}

	return pluginInputs;
}

export default function generateLoadPlugin(options: GenerateLoadPluginOptions = {}): Plugin {
	const output = options.output ?? "src/worker/gen/load.plugin.ts";
	const packageJson = options.packageJson ?? "package.json";
	let root = process.cwd();
	let packageJsonPath = path.resolve(root, packageJson);
	let pluginInputs: PluginInput[] = [];
	let watchedFiles: string[] = [];

	async function writeGeneratedFile(): Promise<void> {
		const outputPath = path.resolve(root, output);
		const source = buildSource(pluginInputs);

		await mkdir(path.dirname(outputPath), { recursive: true });

		let current: string | null = null;
		try {
			current = await readFile(outputPath, "utf8");
		} catch {}

		if (current === source) {
			return;
		}

		await writeFile(outputPath, source);
	}

	async function discoverPluginInputs(resolve: (id: string) => Promise<string | null>): Promise<void> {
		const dependencyNames = await readDependencyNames(packageJsonPath, options.dependencyFields);
		pluginInputs = await resolvePluginInputs(dependencyNames, resolve);
		watchedFiles = pluginInputs.map((input) => input.resolvedId);
	}

	return {
		name: "gotify-load-plugin",
		enforce: "pre",
		configResolved(config) {
			root = config.root;
			packageJsonPath = path.resolve(root, packageJson);
		},
		async buildStart() {
			await discoverPluginInputs(async (id) => (await this.resolve(id))?.id ?? null);
			for (const file of watchedFiles) {
				this.addWatchFile(file);
			}
			await writeGeneratedFile();
		},
		async configureServer(server) {
			await discoverPluginInputs(async (id) => (await server.pluginContainer.resolveId(id))?.id ?? null);
			server.watcher.add(watchedFiles);
			await writeGeneratedFile();
		},
		async handleHotUpdate(ctx) {
			if (watchedFiles.includes(ctx.file)) {
				await writeGeneratedFile();
			}
		},
	};
}
